Дополнительное задание
MihailSergeenkov/redux-start pull request #4
Opened 2020-11-08 13:10 UTC by MihailSergeenkov

2020-11-10 07:32 UTC, index01d requested changes

2020-11-10 07:32 UTC, index01d commented on src/components/Chapter/index.js
> +  sortSections: dispatchProps.sortSections,
ниже видимо переопределяется, так что здесь можно убрать

2020-11-10 07:32 UTC, index01d commented on src/components/Section/index.js
> +    );
по-хорошему выглядит будто это логика по изменению состояния и скорее относится к reducer'у

2020-11-10 07:43 UTC, MihailSergeenkov commented on src/components/Section/index.js
> +    );
Ну у меня логика была такая:
1) Есть один reducer на любое обновление главы, он идет в API, и если успешно, то ответ с измененной главой записывает в store, далее данные обновляются в интерфейсе.
2) Но данные для изменения мне нужно где-то подготовить, причем там где я могу обратиться к store. Вот поэтому я так и сделал, аналогично и с добавлением секции

2020-11-10 07:45 UTC, MihailSergeenkov commented on src/components/Chapter/index.js
> +  sortSections: dispatchProps.sortSections,
Забыл подчистить

2020-11-10 07:47 UTC, MihailSergeenkov commented on src/components/Section/index.js
> +    );
Получается нужно разделить reducer на любое обновление главы, а отдельные reducer?

2020-11-10 17:19 UTC, MihailSergeenkov commented on src/components/Chapter/index.js
> +  sortSections: dispatchProps.sortSections,
Удалил

2020-11-10 17:19 UTC, MihailSergeenkov commented on src/components/Section/index.js
> +    );
Поправил

2020-11-14 21:54 UTC, index01d approved these changes

2020-11-14 21:54 UTC, index01d commented on src/redux/slices/chapters.js
> +    const response = await axios({
Чтобы не дублировать настройку HTTP-клиента можно создать инстанс с помощью метода create https://github.com/axios/axios#axioscreateconfig

Тогда настройку клиента можно будет оттащить в отдельный модуль

2020-11-17 05:26 UTC, merged